language: python
python:
  - "2.7"
  - "pypy"

install:
  - pip install coveralls
  - python setup.py -q install

# command to run tests
script:
  - coverage run --source=compass setup.py test

after_success:
  coveralls
